# Generated by Django 3.2.8 on 2021-11-11 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoDaVendere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('prezzo', models.FloatField(default=0.0)),
                ('tipo', models.CharField(max_length=20)),
                ('aggiunte', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProdottoDaVendere',
                'verbose_name_plural': 'ProdottiDaVendere',
            },
        ),
        migrations.CreateModel(
            name='ProdottoOrdinato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=0)),
                ('prodotto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ordinibar.prodottodavendere')),
            ],
            options={
                'verbose_name': 'ProdottoOrdinato',
                'verbose_name_plural': 'ProdottiOrdinati',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ketchup', models.IntegerField()),
                ('numero_maionesi', models.IntegerField()),
                ('stato', models.CharField(max_length=25)),
                ('orario', models.TimeField(default=0)),
                ('data', models.CharField(default='', max_length=25)),
                ('lista_prodotti', models.ManyToManyField(to='ordinibar.ProdottoOrdinato')),
                ('nome_utente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
