# Generated by Django 3.2.8 on 2021-11-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordinibar', '0002_prodottodavendere_aggiunte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdottoOrdinato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.IntegerField(default=0)),
                ('prodotto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ordinibar.prodottodavendere')),
            ],
            options={
                'verbose_name': 'ProdottoOrdinato',
                'verbose_name_plural': 'ProdottiOrdinati',
            },
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ketchup', models.IntegerField()),
                ('numero_maionesi', models.IntegerField()),
                ('stato', models.CharField(max_length=25)),
                ('lista_prodotti', models.ManyToManyField(to='ordinibar.ProdottoOrdinato')),
                ('nome_utente', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
            },
        ),
    ]
