# Generated by Django 3.2.8 on 2021-11-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinibar', '0002_alter_ordine_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
