# Generated by Django 3.2.8 on 2021-11-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinibar', '0003_ordine_prodottoordinato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordine',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
