# Generated by Django 3.2.8 on 2021-11-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinibar', '0003_alter_ordine_stato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='nome_utente',
        ),
        migrations.AddField(
            model_name='ordine',
            name='id_utente',
            field=models.IntegerField(default=0),
        ),
    ]
