# Generated by Django 3.2.8 on 2021-11-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordinibar', '0004_auto_20211111_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodottoordinato',
            name='prodotto',
        ),
        migrations.AddField(
            model_name='prodottoordinato',
            name='id_prodotto',
            field=models.IntegerField(default=0),
        ),
    ]
